-- Theme:       flat
-- Description: Solarized without the bullshit, redux.
-- Author:      Alex Valiushko (illotum@gmail.com)
-- License:     MIT
-- Source:      https://github.com/illotum/flat.nvim

local theme = {
  -- Syntax
  Normal                   = { fg = "fg", bg = "bg" },
  Terminal                 = { link = "Normal" },
  Type                     = { fg = "yellow" },
  StorageClass             = { link = "Type" },
  Structure                = { link = "Type" },
  Typedef                  = { link = "Type" },
  Constant                 = { fg = "cyan", italic = true },
  Character                = { link = "Constant" },
  Boolean                  = { link = "Constant" },
  String                   = { link = "Constant" },
  Number                   = { link = "Constant" },
  Float                    = { link = "Number" },
  Statement                = { fg = "green" },
  Label                    = { link = "Statement" },
  Operator                 = { link = "Statement" },
  Exception                = { link = "Statement" },
  Conditional              = { link = "Statement" },
  Keyword                  = { link = "Statement" },
  Repeat                   = { link = "Statement" },
  PreProc                  = { fg = "orange" },
  Include                  = { link = "PreProc" },
  Define                   = { link = "PreProc" },
  Macro                    = { link = "PreProc" },
  PreCondit                = { link = "PreProc" },
  Special                  = { fg = "red" },
  SpecialChar              = { link = "Special" },
  Tag                      = { link = "Special" },
  Delimiter                = { link = "Special" },
  SpecialComment           = { link = "Special" },
  Debug                    = { link = "Special" },
  Identifier               = { fg = "blue" },
  Function                 = { link = "Identifier" },
  Comment                  = { fg = "base01", italic = true },
  Underlined               = { fg = "blue", underline = true },
  Todo                     = { fg = "magenta", bold = true },
  Error                    = { fg = "red", bold = true },
  NvimInternalError        = { link = "Error" },
  -- TS Syntax
  ['@field']               = { fg = "fg" },
  -- Editor
  NormalFloat              = { link = "Normal" },
  FloatBorder              = { link = "Normal" },
  FloatShadow              = { bg = "bg", blend = 80 },
  FloatShadowThrough       = { bg = "bg", blend = 100 },
  VertSplit                = { link = "FloatBorder" },
  ColorColumn              = { bg = "base02" },
  Conceal                  = { fg = "base02" },
  Ignore                   = { link = "Conceal" },
  Cursor                   = { fg = "bg", bg = "fg", reverse = true },
  Visual                   = { fg = "base01", bg = "bg", reverse = true },
  StatusLine               = { fg = "base1", bg = "base02", reverse = true },
  StatusLineNC             = { fg = "base00", bg = "base02", reverse = true },
  Tabline                  = { fg = "fg", bg = "base02", sp = "base0", underline = true },
  TabLineFill              = { link = "TabLine" },
  TablineSel               = { fg = "base01", bg = "base2", sp = "base0", underline = true, reverse = true },
  VisualNOS                = { bg = "base02", reverse = true },
  StatusLineTerm           = { link = "StatusLine" },
  StatusLineTermNC         = { link = "StatusLineNC" },
  CursorIM                 = { link = "Cursor" },
  Directory                = { fg = "blue" },
  DiffAdd                  = { fg = "green" },
  DiffChange               = { fg = "yellow" },
  DiffDelete               = { fg = "red", bold = true },
  DiffText                 = { fg = "blue" },
  ErrorMsg                 = { fg = "red", bg = "base3", reverse = true },
  Folded                   = { fg = "base01", italic = true },
  FoldColumn               = { link = "Folded" },
  IncSearch                = { fg = "orange", standout = true },
  MatchParen               = { fg = "fg", bg = "bg", bold = true },
  ModeMsg                  = { fg = "blue" },
  MoreMsg                  = { link = "ModeMsg" },
  NonText                  = { fg = "base00" },
  EndOfBuffer              = { link = "NonText" },
  Pmenu                    = { fg = "base1", bg = "base02" },
  PmenuSel                 = { fg = "base2", bg = "base01" },
  PmenuThumb               = { fg = "base2", bg = "base01" },
  PmenuSbar                = { fg = "base1", bg = "base02" },
  Question                 = { fg = "cyan" },
  Search                   = { fg = "yellow", reverse = true },
  CurSearch                = { link = "Search" },
  QuickFixLine             = { link = "Search" },
  SpellBad                 = { fg = "red", italic = true, undercurl = true },
  SpellCap                 = { fg = "violet", italic = true, undercurl = true },
  SpellLocal               = { fg = "yellow", italic = true, undercurl = true },
  SpellRare                = { fg = "cyan", italic = true, undercurl = true },
  Title                    = { fg = "orange" },
  WildMenu                 = { fg = "base2", bg = "base02", reverse = true },
  LineNr                   = { fg = "base01" },
  CursorLine               = { bg = "base02" },
  CursorColumn             = { link = "CursorLine" },
  ToolbarLine              = { link = "CursorLine" },
  CursorLineNr             = { link = "CursorLine" },
  SpecialKey               = { link = "Normal" },
  SignColumn               = { fg = "base01" },
  -- Diagnostic
  DiagnosticError          = { fg = "red" },
  DiagnosticInfo           = { fg = "green" },
  DiagnosticWarn           = { fg = "yellow" },
  DiagnosticHint           = { fg = "fg" },
  DiagnosticOk             = { fg = "cyan" },
  DiagnosticDeprecated     = { fg = "base01" },
  DiagnosticUnderlineError = { sp = "red", undercurl = true },
  DiagnosticUnderlineInfo  = { sp = "green", undercurl = true },
  DiagnosticUnderlineWarn  = { sp = "yellow", undercurl = true },
  DiagnosticUnderlineHint  = { sp = "fg", undercurl = true },
  DiagnosticUnderlineOk    = { sp = "cyan", undercurl = true },
  -- Cmp
  CmpItemAbbrDeprecated    = { link = "DiagnosticDeprecated" },
  CmpItemAbbrMatch         = { fg = "base2" },
  CmpItemAbbrMatchFuzzy    = { link = "CmpItemAbbrMatch" },
  CmpItemMenu              = { link = "Comment" },
  CmpItemKind              = { link = "Comment" },
  CmpItemKindClass         = { link = "@lsp.type.class" },
  CmpItemKindConstant      = { link = "@constant" },
  CmpItemKindConstructor   = { link = "@constructor" },
  CmpItemKindModule        = { link = "@include" },
  CmpItemKindEnum          = { link = "@lsp.type.enum" },
  CmpItemKindEnumMember    = { link = "@lsp.type.enumMember" },
  CmpItemKindField         = { link = "@field" },
  CmpItemKindFunction      = { link = "@function" },
  CmpItemKindInterface     = { link = "@lsp.type.interface" },
  CmpItemKindKeyword       = { link = "@keyword" },
  CmpItemKindMethod        = { link = "@lsp.type.method" },
  CmpItemKindOperator      = { link = "@operator" },
  CmpItemKindProperty      = { link = "@property" },
  CmpItemKindReference     = { link = "@text.reference" },
  CmpItemKindStruct        = { link = "@lsp.type.struct" },
  CmpItemKindText          = { link = "@text.literal" },
  CmpItemKindUnit          = { link = "@constant.macro" },
  CmpItemKindValue         = { link = "@constant.macro" },
  CmpItemKindVariable      = { link = "@variable" },
  CmpItemKindType          = { link = "@type" },
  CmpItemKindTypeParameter = { link = "@type.definition" },
  CmpItemKindSnippet       = { link = "@macro" },
}

-- Apply theme --

local flat = require("flat")
flat.setup({ palette = "solarized_new" })

vim.cmd("hi clear")

if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

for group, hl in pairs(theme) do
  hl = vim.tbl_extend("force", hl, {
    fg = flat.hex(hl.fg),
    bg = flat.hex(hl.bg),
    sp = flat.hex(hl.sp),
    ctermfg = flat.term(hl.fg),
    ctermbg = flat.term(hl.bg),
  })
  vim.api.nvim_set_hl(0, group, hl)
end

vim.g.colors_name = "flat"
